openapi: 3.1.0
info: {title: AskAssistant, version: "1.0"}
paths:
  /ask:
    post:
      summary: Query the company knowledge assistant
      operationId: askAssistant
      security: [apiKeyAuth: []]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                conversation_id:
                  type: string
                  description: "Opaque ID returned from previous calls"
                query:
                  type: string
                  description: "Exact user question"
              required: [query]
      responses:
        "200":
          description: Assistant reply
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversation_id: {type: string}
                  answer:          {type: string}
components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
